# 内容所在的子目录，将显示在首页和归档页
mainSections = ["post"]
# 在 RSS 中输出全文
rssFullContent = true
favicon        = "img/favicon.jpg"

# 排序方式: "default", "lastmod"
SortBy              = "default"

[footer]
    customText = ""

[dateFormat]
    # 使用当地日期格式
    published   = ":date_medium"
    lastUpdated = ":date_medium"

[sidebar]
    emoji    = ""
    subtitle = """
这是才华横溢的年代，也是愚昧无知的年代。
这是信仰坚定的时期，也是怀疑一切的时期。
"""
    avatar   = "img/avatar.jpg"

[article]
    headingAnchor = true
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "采用 CC BY-NC-SA 4.0 许可协议"
