# 内容所在的子目录，将显示在首页和归档页
mainSections = ["post"]
# 在 RSS 中输出全文
rssFullContent = true
favicon        = "img/favicon.jpg"

# 排序方式: "default", "lastmod"
SortBy              = "default"

[footer]
    customText = ""

[dateFormat]
    # 使用当地日期格式
    published   = ":date_medium"
    lastUpdated = ":date_medium"

[sidebar]
    emoji    = ""
    subtitle = """
这是美好的日子，也是苦难的日子。
这是才华横溢的年代，也是愚昧无知的年代。
这是信仰坚定的时期，也是怀疑一切的时期。
这是灿烂辉煌的季节，也是黯淡无光的季节。
这是希望的春天，也是绝望的冬天。
我们拥有选择一切的机会，我们其实一无所有。
我们走在通向天堂的道路上，我们正坠入万劫不复的地狱。
"""
    avatar   = "img/avatar.jpg"

[article]
    headingAnchor = true
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "采用 CC BY-NC-SA 4.0 许可协议"
